import CoreExactness.Prelude
import CoreExactness.RowVacuity
import CoreExactness.PolyVacuity
import CoreExactness.BoundedExactness
import CoreExactness.RowwiseExactness
import CoreExactness.EuclideanSemantics
import CoreExactness.RangeExclusion
